version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install -g yarn
      - yarn install
  build:
    commands:
      - echo "Building React application..."
      - yarn build
  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'
  base-directory: build
