version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - pwd  # Print current working directory for debugging
      - ls -al  # List contents of current directory for debugging
      - cd media || exit 1  # Change directory to 'media' or exit with error code 1 if unsuccessful
      - ls -al  # List contents of 'media' directory for debugging
      - echo "Installing source NPM dependencies..."
      - npm install
  build:
    commands:
      - echo Build started on 'date'
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: 'media/build'
