version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo "Current directory contents:"
      - ls -al
      - cd media
      - echo "Changed directory to media"
      - echo "Installing source NPM dependencies..."
      - npm install
  build:
    commands:
      - echo Build started on 'date'
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: 'media/build'
