version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14   # Specify Node.js runtime version
    commands:
      - npm install -g yarn  # Install Yarn globally

  pre_build:
    commands:
      - yarn install  # Install project dependencies using Yarn

  build:
    commands:
      - yarn build  # Run the build script to build the React application

artifacts:
  files:
    - '**/*'  # Include all files in the build artifacts
  base-directory: 'build'  # Set the base directory for artifacts to the build output directory
