version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # Install Node.js 12
      - echo "Installing Node.js 12..."
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
      # Install Yarn
      - echo "Installing Yarn..."
      - npm install -g yarn
  pre_build:
    commands:
      # Print Yarn version
      - echo "Yarn version:"
      - yarn --version
      # Print Node.js version
      - echo "Node.js version:"
      - node --version
      # Install project dependencies
      - echo "Installing project dependencies..."
      - yarn install --verbose --check-files --network-timeout 1000000
  build:
    commands:
      # Build React application
      - echo "Building React application..."
      - yarn build
  post_build:
    commands:
      # Print build output directory contents
      - echo "Build output directory contents:"
      - ls -al build/

artifacts:
  files:
    - '**/*'
  base-directory: build
